name: Build CI-Test

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-windows:
    runs-on: 	windows-latest
    strategy:
      matrix:
        node_version:
          - 10
        node_arch:
          - x86

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v5
      with:
        setupOnly: true
    # Now that vcpkg is installed, it is being used to run desired arguments.
    - run: |
        $VCPKG_ROOT/vcpkg @$vcpkgResponseFile
        $VCPKG_ROOT/vcpkg install openssl-windows:x86-windows
      shell: bash
    - name: Node ${{ matrix.node_version }} - ${{ matrix.node_arch }} on ${{ matrix.os }}
      uses: aminya/setup-node@x86
      with:
        node-version: ${{ matrix.node_version }}
        node-arch: ${{ matrix.node_arch }}
    - name: Build
      run: set npm_config_cache= && set NPM_CONFIG_CACHE= && npm install --build-from-source
      env:
        CI: true
    - name: Test
      run: npm run test
      env:
        CI: true  
    - name: Upload 
      run: node_modules/.bin/prebuild --upload -u ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true  
  
