name: Build - Mac M1

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - v*


  # OpenSSL
  # Instead of downloading binaries from somewhere, it is better to use Homebrew to install OpenSSL.
  #      - name: Install OpenSSL
  #      run: |
  #        wget https://mac.r-project.org/bin/darwin20/arm64/openssl-1.1.1o-darwin.20-arm64.tar.xz
  #        tar -xf openssl-1.1.1o-darwin.20-arm64.tar.xz -C /tmp
  #        rm -rf openssl-1.1.1o-darwin.20-arm64.tar.xz



env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-macos:
    runs-on: macos-13
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install OpenSSL
        run: HOMEBREW_NO_INSTALL_CLEANUP=1 brew reinstall openssl@3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm install --ignore-scripts
          node_modules/.bin/prebuild -r napi --backend cmake-js --arch arm64 --upload -u ${{ secrets.GITHUB_TOKEN }} -- --CDCMAKE_OSX_ARCHITECTURES="arm64"
        env:
          CI: true
