name: Build Test

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: arm32v7/ubuntu:xenial
    steps:  
    - uses: actions/checkout@v2
    - name: What OS is running
      run: apt update
    - name: What java version do we have
      run: apt install libssl-dev
     
