name: Build Test

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  testbox:
    runs-on: ubuntu-latest
    container: arm32v7/ubuntu:xenial
    steps:  
      - run: |
           apt update
           apt install libssl-dev
      - uses: actions/checkout@v2
     
